POST http://i9c110.p.ssafy.io:8083/users/join
Content-Type: application/json

{
  "userId": "qjawls123",
  "name": "parkbumjin",
  "password": "qpal123!"
}

###

POST http://i9c110.p.ssafy.io:8083/auth/login
Content-Type: application/json

{
  "userId": "qjawls123",
  "password": "qpal123!"
}

