GET localhost:8083/community/info/1
Content-Type: application/json

###
GET localhost:8083/api/community/all/0
Content-Type: application/json

###
GET localhost:8083/api/community/detail/xodnjs8287@naver.com
Content-Type: application/json

###
GET localhost:8083/api/community/likes/xodnjs8287@naver.com
Content-Type: application/json