POST http://localhost:8083/create-image
Content-Type: application/json

{
  "prompt": "high quality, painting.  Harry and James in the spaceship ",
  "negative_prompt": "low quality, low contrast, draft, amateur, cut off, cropped, frame, scary"
}

###

POST http://localhost:8083/create-chat
Content-Type: application/json

{
"chatGptRequest": {
  "messages": [
    {
      "role": "system",
      "content": "You are a helpful assistant."
    },
    {
      "role": "user",
      "content": "1 "
    }
  ]

},
  "userChoiceRequest": {
    "backGround": "산",
    "player1": "범진",
    "player2": "범진2",
    "player1Character": "용감한",
    "player2Character": "소심한",
    "turn": "50"

  },
  "pageDtoRequest": {
    "taleId": 1
  }


}
