POST http://localhost:8083/users/join
Content-Type: application/json

{
  "userId": "xodnjs8287@naver.com",
  "name": "park bumjin",
  "password": "qpal123!"
}

###

POST http://i9c110.p.ssafy.io:8083/auth/login
Content-Type: application/json

{
  "userId": "qjawls123",
  "password": "qpal123!"
}

###
GET http://localhost:8083/users/qjawls123@naver.com
Content-Type: application/json
