version: '2.19.1'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ssafy
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    volumes:
      - db-data:/var/lib/mysql

  myapp:
    image: test
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3305/ssafy/useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8083:8080"

volumes:
  db-data: